version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: vlad6243/node-test
    ports:
      - 5000:5000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
